[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.5.1"
  YARN_FLAGS = "--no-ignore-optional"

[context.production]
  environment = {ACCESS_TOKEN = "AqmTTGg9qeEpwQA7nSEJ7Z5yArqft6", PASSWORD = "jd2019"}